;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ace-jump-char-mode
	ace-jump-move
	counsel-M-x
	indent-for-tab-command
	mark-sexp
	swiper
	wdired-next-line
	wdired-previous-line
	whole-line-or-region-kill-region
	whole-line-or-region-kill-ring-save
	whole-line-or-region-yank
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	))
