;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ace-jump-char-mode
	ace-jump-move
	c-electric-delete-forward
	counsel-M-x
	electric-newline-and-maybe-indent
	indent-for-tab-command
	isearch-forward-regexp
	isearch-printing-char
	mark-sexp
	sp-delete-char
	sp-kill-word
	swiper
	wdired-next-line
	wdired-previous-line
	wdired-upcase-word
	whole-line-or-region-kill-region
	whole-line-or-region-kill-ring-save
	whole-line-or-region-yank
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	dired-previous-line
	end-of-buffer
	helm-buffers-list
	sp-backward-delete-char
	wdired-finish-edit
	))
